apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-matan
  #namespace: "web1"
spec:
  selector:
    matchLabels:
      app: nginx-matan
  serviceName: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-matan
    spec:
      containers:
      - name: nginx-matan
        image: matanbedani/webserver:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www
        hostPath:
          path: /home/matan/nginx
          
          
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-matan
spec:
  ports:
  - port: 80
    name: web
  #type: clusterIP
  selector:
    app: nginx-matan